# version: "3.9"
services:
  webapp:
    build: ./webapp
    ports:
      - "3000:3000"
    volumes:
      - db-data:/app/prisma/
    depends_on:
      - model
    # environment:
    #   - DATABASE_URL=file:./prisma/dev.db # Adjust if needed for SQLite

  model:
    build: ./server/model
    ports:
      - "5000:5000"
    # environment:
    #   - FLASK_RUN_HOST=0.0.0.0
  
volumes:
  db-data: